let nodeData;

nodeData = {
    // faculty id and names
    "nodes": [
        {   "id": 1762,
            "name": "Amir Yacoby",
            "researchInterests": "Quantum Engineering",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Professor of Physics and of Applied Physics",
            "location": "LISE",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Yacoby_200x300.jpg?itok=FrGXO40_"},
        {   "id": 2626,
            "name": "Ann Pearson",
            "researchInterests": ["Biogeochemical Cycles","Climate Change", "Oceanography"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Murray and Martha Ross Professor of Environmental Sciences; Affiliate in Environmental Science & Engineering",
            "location": "Hoffman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-12/Pearson_200x300.jpg?itok=ZX2yBPve"},
        {   "id": 1795,
            "name": "Ariel Amir",
            "researchInterests": ["Control Theory and Stochastic Systems","Modeling Physical/Biological Phenomena and Systems","Biomaterials","Materials","Soft Matter"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "Thomas D. Cabot Associate Professor of Applied Mathematics and Applied Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Amir_200x300_0.jpg?itok=sOHVJP3H"},
        {   "id": 13261,
            "name": "Ariel Procaccia",
            "researchInterests": ["Economics and Computation", "Theory of Computation","Artificial Intelligence","Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-02/Procaccia_200x300.jpg?itok=UMKqCrs4"},
        {   "id": 1523,
            "name": "Barbara J. Grosz",
            "researchInterests": "Artificial Intelligence",
            "teachingArea": "Computer Science",
            "primaryTitle": "Higgins Research Professor of Natural Sciences",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-11/grosz_headshot.jpeg?itok=xzF_4b7B"},
        {   "id": 1835,
            "name": "Boaz Barak",
            "researchInterests": ["Theory of Computation","Artificial Intelligence","Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Barak_200x300.jpg?itok=ANPBgStM"},
        {   "id": 2414,
            "name": "Boris Kozinsky",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Materials","Quantum Engineering","Soft Matter","Computational and Data Science","Surface and Interface Science"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Associate Professor of Computational Materials Science",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Kozinsky_200x300.jpg?itok=ktChn1qg"},
        {   "id": 1524,
            "name": "Brian F. Farrell",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Climate Change","Climate Dynamics","Meteorology"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Robert P. Burden Professor of Meteorology",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/farrell_200x300_0.jpg?itok=oYv9-BqZ"},
        {   "id": 2711,
            "name": "Cengiz Pehlevan",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Bioinspired Robotics and Computing","Biomechanics and Motor Control","Artificial Intelligence","Computational Neuroscience","Signal Processing"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "Assistant Professor of Applied Mathematics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Pehlevan_200x300_0.jpg?itok=cANq-1pZ"},
        {   "id": 1733,
            "name": "Charles M. Lieber",
            "researchInterests": ["Biomaterials","Materials","Soft Matter","Biomechanics and Motor Control","Cell and Tissue Engineering, Biomaterials, and Therapeutics","Surface and Interface Science"],
            "teachingArea": null,
            "primaryTitle": "Joshua and Beth Friedman University Professor",
            "location": "Mallinckrodt",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Leiber_200x300.jpg?itok=8i3Hy4UR"},
        {   "id": 1576,
            "name": "Cherry Murray",
            "researchInterests": "Science and Technology Policy",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Benjamin Peirce Professor of Technology and Public Policy and Professor of Physics, Emerita",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Murray_200x300.jpg?itok=RvxlYmmh"},
        {   "id": 11536,
            "name": "Christin Y. Sander",
            "researchInterests": ["Bioinspired Robotics and Computing","Cell and Tissue Engineering, Biomaterials, and Therapeutics","Computational Neuroscience"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "Assistant Professor of Radiology",
            "location": "Athinoula A. Martinos Center for Biomedical Imaging",
            "image": "http://www.nmr.mgh.harvard.edu/~sander/fig.JPG"},
        {   "id": 1760,
            "name": "Christopher Rycroft",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems", "Soft Matter", "Cell and Tissue Engineering, Biomaterials, and Therapeutics", "Fluid Mechanics", "Solid Mechanics","Surface and Interface Science"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "John L. Loeb Associate Professor of Engineering and Applied Sciences",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Rycroft_200x300.jpg?itok=VAtPIkQd"},
        {   "id": 11541,
            "name": "Christopher W. Tanner",
            "researchInterests": "Computational and Data Science",
            "teachingArea": ["Computer Science","Applied Computation"],
            "primaryTitle": "Lecturer on Computational Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-01/Chris_Tanner.png?itok=EumVhqUf"},
        {   "id": 1667,
            "name": "Conor J Walsh",
            "researchInterests": ["Materials","Bioinspired Robotics and Computing","Biomechanics and Motor Control","Robotics and Control","Solid Mechanics","Science and Engineering Education"],
            "teachingArea": ["Materials Science & Mechanical Engineering","Bioengineering"],
            "primaryTitle": "Paul A. Maeder Professor of Engineering and Applied Sciences",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Walsh_200x300.jpg?itok=6zc1Uu0y"},
        {   "id": 1865,
            "name": "Cynthia Dwork",
            "researchInterests": ["Theory of Computation|Information and Society|Science and Technology Policy"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Dwork_200x300.jpg?itok=jlJr0K1q"},
        {   "id": 1554,
            "name": "Cynthia Friend",
            "researchInterests": ["Materials","Surface and Interface Science"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Theodore William Richards Professor of Chemistry and Professor of Materials Science",
            "location": "Mallinckrodt",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Friend_200x300.jpg?itok=qYUV5Gt2"},
        {   "id": 1559,
            "name": "Daniel J. Jacob",
            "researchInterests": ["Atmospheric Chemistry","Climate Change","Global Contaminants"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Vasco McCoy Family Professor of Atmospheric Chemistry and Environmental Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Jacob_200x300.jpg?itok=YTWhXTJ9"},
        {   "id": 1734,
            "name": "Daniel Needleman",
            "researchInterests": ["Materials","Soft Matter","Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Gordon McKay Professor of Applied Physics and Professor of Molecular and Cellular Biology",
            "location": "Northwest Building",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Needleman_200x300.jpg?itok=KQFNfT3P"},
        {   "id": 1636,
            "name": "Daniel P. Schrag",
            "researchInterests": ["Biogeochemical Cycles","Climate Change","Climate Dynamics","Energy Resources and Energy Systems","Oceanography","Solar Geoengineering","Energy, Environment, and Sustainability","Science and Technology Policy"],
            "teachingArea":"Environmental Science & Engineering",
            "primaryTitle": "Sturgis Hooper Professor of Geology and Professor of Environmental Science and Engineering",
            "location": "MCZ",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-10/Schrag_200x300.jpg?itok=SVFcZm1s"},
        {   "id": 1544,
            "name": "David A. Weitz",
            "researchInterests": ["Materials","Soft Matter","Biomechanics and Motor Control","Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Mallinckrodt Professor of Physics and of Applied Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Weitz_200x300.jpg?itok=xNZcQbBs"},
        {   "id": 1542,
            "name": "David Brooks",
            "researchInterests": ["Architecture","Computer Engineering and Architecture"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Haley Family Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-02/Brooks2.jpg?itok=CDs59D2I"},
        {   "id": 1617,
            "name": "David C. Bell",
            "researchInterests": ["Materials","Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Gordon McKay Professor of the Practice of Electron Microscopy",
            "location": "McKay",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/dcb_200x300.jpg?itok=Lc1zwB5S"},
        {   "id": 1731,
            "name": "David Clarke",
            "researchInterests": ["Materials","Soft Matter","Robotics and Control"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Extended Tarr Family Professor of Materials",
            "location": "Cruft",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Clarke_200x300.jpg?itok=gOXR2WuH"},
        {   "id": 1543,
            "name": "David J. Malan",
            "researchInterests": ["Science and Engineering Education","Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of the Practice of Computer Science",
            "location": "Maxwell Dworkin",
            "image" : "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/malan.jpg?itok=K6tXq7-Y"},
        {   "id": 1688,
            "name": "David Keith",
            "researchInterests": ["Atmospheric Chemistry","Climate Change","Energy Resources and Energy Systems","Solar Geoengineering","Energy, Environment, and Sustainability","Science and Technology Policy"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Gordon McKay Professor of Applied Physics",
            "location": "Mallinckrodt",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Keith_200x300.jpg?itok=hZQKjsB1"},
        {   "id": 1579,
            "name": "David Mooney",
            "researchInterests": ["Cell and Tissue Engineering", "Biomaterials, and Therapeutics", "Biomechanics and Motor Control"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "Robert P. Pinkas Family Professor of Bioengineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Mooney_200x300.jpg?itok=SVqT614I"},
        {   "id": 1727,
            "name": "David Parkes",
            "researchInterests": ["Economics and Computation","Artificial Intelligence","Computational and Data Science","Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "George F. Colony Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Parkes_200x300.jpg?itok=He23_TG7"},
        {   "id": 1627,
            "name": "David R. Nelson",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Biomaterials"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Arthur K. Solomon Professor of Biophysics and Professor of Physics and Applied Physics",
            "location": "Lyman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Nelson_200x300.jpg?itok=NSlk8OFf"},
        {   "id": 2015,
            "name": "David Sondak",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Computational and Data Science","Fluid Mechanics","Science and Engineering Education"],
            "teachingArea": "Applied Computation",
            "primaryTitle": "Lecturer on Computational Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/dsondak_200x300.jpg?itok=dZIfRitm"},
        {   "id": 1802,
            "name": "Demba Ba",
            "researchInterests": ["Signal Processing","Science and Engineering Education","Modeling Physical/Biological Phenomena and Systems","Control Theory and Stochastic Systems","Computational Neuroscience","Computational and Data Science","Bioinspired Robotics and Computing","Artificial Intelligence"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Associate Professor of Electrical Engineering and Bioengineering",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Ba_200x300.jpg?itok=UNHcWkt2"},
        {   "id": 1887,
            "name": "Doeke Romke Hekstra",
            "researchInterests": "Soft Matter",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Assistant Professor of Molecular and Cellular Biology and of Applied Physics",
            "location": "Northwest Building",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/hekstra_200x300.jpg?itok=FGidpkSK"},
        {   "id": 1650,
            "name": "Donald Elliot Ingber",
            "researchInterests": ["Biomechanics and Motor Control,Cell and Tissue Engineering, Biomaterials, and Therapeutics"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "Founding Director, Wyss Institute for Biologically Inspired Engineering at Harvard University",
            "location": "Children's Hospital",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Ingber_200x300.jpg?itok=GWdoJKic"},
        {   "id": 1538,
            "name": "Donhee Ham",
            "researchInterests": ["Biomaterials","Quantum Engineering","Bioinspired Robotics and Computing","Cell and Tissue Engineering, Biomaterials, and Therapeutics","Circuits and VLSI","Computer Engineering and Architecture"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Gordon McKay Professor of Electrical Engineering and Applied Physics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-03/Ham_200x300.jpg?itok=dNNh44EB"},
        {   "id": 1685,
            "name": "Eddie Kohler",
            "researchInterests": "Systems, Networks, and Databases",
            "teachingArea": "Computer Science",
            "primaryTitle":"Microsoft Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Kohler_200x300.jpg?itok=Xs-C9lEa"},
        {   "id": 1551,
            "name": "Efthimios Kaxiras",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Materials","Computational and Data Science","Surface and Interface Science"],
            "teachingArea": ["Applied Physics,Applied Mathematics"],
            "primaryTitle": "John Hasbrouck Van Vleck Professor of Pure and Applied Physics and of Applied Mathematics",
            "location": "Lyman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Kaxiras_200x300.jpg?itok=ZYJ7io-5"},
        {   "id": 2929,
            "name": "Elena Leah Glassman",
            "researchInterests": ["Graphics, Vision, Visualization, and Interaction","Programming Languages"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Assistant Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Glassman_200x300.jpg?itok=gKYskYF7"},
        {   "id": 1571,
            "name": "Eli Tziperman",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Climate Change","Climate Dynamics","Ice Dynamics and Sea Level","Oceanography","Planetary Sciences","Fluid Mechanics"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Pamela and Vasco McCoy, Jr. Professor of Oceanography and Applied Physics",
            "location": "Hoffman Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Tziperman_200x300.jpg?itok=ioR-n4qs"},
        {   "id": 1607,
            "name": "Elsie M Sunderland",
            "researchInterests": ['Biogeochemical Cycles','Climate Change','Oceanography','Global Contaminants','Water'],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Gordon McKay Professor of Environmental Chemistry",
            "location":"Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Sunderland_200x300.jpg?itok=2ClG4njc"},
        {   "id": 1561,
            "name": "Eric Mazur",
            "researchInterests": ["Photonics","Science and Engineering Education"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Balkanski Professor of Physics and Applied Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Mazur_200x300.jpg?itok=2aYFeqjK"},
        {   "id": 1545,
            "name": "Evelyn Hu",
            "researchInterests": ["Materials","Photonics"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Tarr-Coyne Professor of Applied Physics and of Electrical Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Hu_200x300.jpg?itok=FoBGDmzY"},
        {   "id": 1580,
            "name": "Federico Capasso",
            "researchInterests": "Photonics",
            "teachingArea": "Applied Physics",
            "primaryTitle":"Robert L. Wallace Professor of Applied Physics and Vinton Hayes Senior Research Fellow in Electrical Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Capasso_200x300.jpg?itok=2qsutDn2"},
        {   "id": 1695,
            "name":	"Finale Doshi-Velez",
            "researchInterests": ["Computational and Data Science","Artificial Intelligence"],
            "teachingArea": "Computer Science",
            "primaryTitle": "John L. Loeb Associate Professor of Engineering and Applied Sciences",
            "location": "Science Center",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Doshi_200x300.jpg?itok=7S_hVi1H"},
        {   "id": 1864,
            "name":	"Flavio P. Calmon",
            "researchInterests": ["Theory of Communication","Signal Processing","Information and Society","Control Theory and Stochastic Systems"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Assistant Professor of Electrical Engineering",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Calmon_200x300.jpg?itok=HsYPiacv"},
        {   "id": 1824,
            "name":	"Frank J. Doyle",
            "researchInterests": ["Control Theory and Stochastic Systems","Modeling Physical/Biological Phenomena and Systems","Bioinspired Robotics and Computing","Cell and Tissue Engineering, Biomaterials, and Therapeutics","Computational Neuroscience","Signal Processing","Science and Engineering Education","Science and Technology Policy"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "John A. Paulson Dean",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Doyle_200x300.jpg?itok=LHAh9f4F"},
        {   "id": 1815,
            "name":	"Frank N Keutsch",
            "researchInterests": ["Atmospheric Chemistry","Climate Change","Solar Geoengineering"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Stonington Professor of Engineering and Atmospheric Science and Professor of Chemistry and Chemical Biology",
            "location": "Mallinckrodt",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Keutsch_300x200.jpg?itok=QvqYrARZ"},
        {   "id": 1581,
            "name":	"Frans A. Spaepen",
            "researchInterests": ["Materials","Soft Matter","Surface and Interface Science"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "John C. and Helen F. Franklin Professor of Applied Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Spaepen_200x300.jpg?itok=XtaBtcXP"},
        {   "id": 1563,
            "name":	"Gu-Yeon Wei",
            "researchInterests": ["Computer Engineering and Architecture","Circuits and VLSI","Architecture"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Robert and Suzanne Case Professor of Electrical Engineering and Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Wei_200x300.jpg?itok=VRUqmbtV"},
        {   "id": 1575,
            "name":"H.T. Kung",
            "researchInterests": ["Architecture","Systems, Networks, and Databases","Computer Engineering and Architecture","Signal Processing"],
            "teachingArea": "Computer Science",
            "primaryTitle": "William H. Gates Professor of Computer Science and Electrical Engineering and Vinton Hayes Senior Research Fellow in Electrical Engineering",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-01/HT_Kung.png?itok=ADBFK1xE"},
        {   "id": 1566,
            "name": "Hanspeter Pfister",
            "researchInterests": ["Graphics, Vision, Visualization, and Interaction","Computational and Data Science"],
            "teachingArea": "Computer Science",
            "primaryTitle": "An Wang Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Pfister_200x300_0.jpg?itok=cErFwn0E"},
        {   "id": 1533,
            "name": "Harry R. Lewis",
            "researchInterests": ["Theory of Computation","Information and Society","Communications and Internet Policy","Science and Technology Policy"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Research Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Lewis.Harry_200x300_0.jpg?itok=fIXb8Csj"},
        {   "id": 1732,
            "name":	"James G. Anderson",
            "researchInterests": ["Atmospheric Chemistry","Climate Change","Solar Geoengineering"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Philip S. Weld Professor of Atmospheric Chemistry",
            "location": "Mallinckrodt",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Anderson_200x300.jpg?itok=ZxRNwV3D"},
        {   "id": 1660,
            "name":	"James H. Waldo",
            "researchInterests": ["Systems, Networks, and Databases","Information and Society","Computational and Data Science"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of the Practice of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/JWALDO.jpg?itok=1RMspzDg"},
        {   "id": 1822,
            "name":	"James Mickens",
            "researchInterests": ["Systems, Networks, and Databases","Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Mickens_200x300.jpg?itok=xyxnyTeL"},
        {   "id": 1548,
            "name":	"James R. Rice",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems","Materials","Climate Change","Geophysics","Ice Dynamics and Sea Level","Fluid Mechanics","Solid Mechanics"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle":  "Professor of Engineering Sciences and Geophysics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Rice_200x300.jpg?itok=inOr8b8P"},
        {   "id": 1715,
            "name":	"Jennifer Lewis",
            "researchInterests": ["Materials|Soft Matter|Cell and Tissue Engineering, Biomaterials, and Therapeutics|Surface and Interface Science|Science and Engineering Education"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle":  "Hansjorg Wyss Professor of Biologically Inspired Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Lewis_200x300.jpg?itok=aVoc-c87"},
        {   "id": 1877,
            "name":	"Jenny Hoffman",
            "researchInterests": ["Materials|Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle":  "Clowes Professor of Science",
            "location": "Lyman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Hoffman_200x300.jpg?itok=Dnog0md6"},
        {   "id": 2622,
            "name": "Jerry X. Mitrovica",
            "researchInterests": ["Climate Change|Climate Dynamics|Geophysics|Ice Dynamics and Sea Level|Planetary Sciences"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle":  "Frank B. Baird, Jr. Professor of Science",
            "location": "Geological Museum",
            "image": "https://projects.iq.harvard.edu/files/styles/profile_full/public/mitrovicagroup/files/jerry_mitrovica.jpg?m=1593025361&itok=rWb4E2s0"},
        {   "id": 2715,
            "name":	"Jia Liu",
            "researchInterests": ["Biomaterials","Materials","Bioinspired Robotics and Computing","Cell and Tissue Engineering, Biomaterials, and Therapeutics","Computational Neuroscience|Signal Processing|Science, Technology, Innovation, and Public Policy|Science and Engineering Education"],
            "teachingArea": "Bioengineering",
            "primaryTitle":  "Assistant Professor of Bioengineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Liu_200x300.jpg?itok=qstrqj5C"},
        {   "id": 1527,
            "name":	"Joanna Aizenberg",
            "researchInterests": ["Biomaterials|Materials|Soft Matter|Biomechanics and Motor Control|Global Contaminants|Water|Surface and Interface Science|Energy, Environment, and Sustainability"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle":  "Amy Smith Berylson Professor of Materials Science and Professor of Chemistry & Chemical Biology",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Aizenberg_200x300.jpg?itok=MPrTA3HP"},
        {   "id": 1852,
            "name":	"John H. Shaw",
            "researchInterests": ["Climate Change|Energy Resources and Energy Systems|Geophysics|Energy, Environment, and Sustainability"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle":  "Harry C. Dudley Professor of Structural and Economic Geology and Professor of Environmental Science and Engineering",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Shaw_200x300_0.jpg?itok=uk7tjiHu"},
        {   "id": 2621,
            "name":	"John P. Holdren",
            "researchInterests": ["Climate Change|Energy Resources and Energy Systems|Energy, Environment, and Sustainability|Science and Technology Policy"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Teresa and John Heinz Professor of Environmental Policy; Affiliate in Environmental Science & Engineering",
            "location": "Belfer",
            "image": "https://upload.wikimedia.org/wikipedia/commons/d/da/John_Holdren_at_commercial_human_spaceflight_press_conference_%28201002020002HQ%29.jpg"},
        {   "id": 1639,
            "name":	"Jonathan Zittrain",
            "researchInterests": ["Artificial Intelligence|Information and Society|Communications and Internet Policy|Science and Technology Policy"],
            "teachingArea": "Computer Science",
            "primaryTitle": "George Bemis Professor of Law",
            "location": "Griswold",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Zittrain_200x300.jpg?itok=o5XGybUC"},
        {   "id": 1578,
            "name":	"Joost J. Vlassak",
            "researchInterests": ["Materials","Soft Matter","Solid Mechanics","Surface and Interface Science"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Abbott and James Lawrence Professor of Materials Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Vlassak_200x300.jpg?itok=LNyaEyuh"},
        {   "id": 1875,
            "name":	"Joze Bevk",
            "researchInterests": ["Materials","Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Senior Research Fellow in Applied Physics",
            "location": null,
            "image": "https://media-exp1.licdn.com/dms/image/C5103AQFregtKF-uMYw/profile-displayphoto-shrink_400_400/0/1517504499567?e=1611187200&v=beta&t=LmQojRhJePUtk8Vr-slV_XraoacF0EsPIxThzeHff2g"},
        {   "id":11701,
            "name":	"Julia A. Mundy",
            "researchInterests": "Materials",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Assistant Professor of Physics; Affiliate in Applied Physics",
            "location": "LISE",
            "image": "http://mundy.physics.harvard.edu/images/Julia%20Mundy.jpg"},
         {  "id":2544,
             "name": "Kaighin A McColl",
             "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Climate Change|Climate Dynamics|Meteorology|Water|Fluid Mechanics"],
             "teachingArea": "Environmental Science & Engineering",
             "primaryTitle": "Assistant Professor of Earth and Planetary Sciences and of Environmental Science and Engineering",
             "location": null,
             "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/McColl.jpg?itok=N5-ngolN"},
        {   "id":2671,
            "name": "Karen Brennan",
            "researchInterests": "Information and Society",
            "teachingArea": "Computer Science",
            "primaryTitle": "Associate Professor of Education; Affiliate in Computer Science",
            "location": "Longfellow",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Brennan_200x300.jpg?itok=6qB1Ciq6"},
        {   "id": 1598,
            "name": "Katia Bertoldi",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Materials|Solid Mechanics"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "William and Ami Kuan Danoff Professor of Applied Mechanics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Bertoldi_200x300.jpg?itok=VJXCqfNg"},
        {   "id": 1577,
            "name": "Kit Parker",
            "researchInterests": ["Biomechanics and Motor Control|Cell and Tissue Engineering, Biomaterials, and Therapeutics"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "Tarr Family Professor of Bioengineering and Applied Physics",
            "location": "Pierce",
            "image":"http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Parker_200x300.jpg?itok=Rqr0aITn"},
        {   "id":1611,
            "name": "Krzysztof Z Gajos",
            "researchInterests": ["Artificial Intelligence|Graphics, Vision, Visualization, and Interaction|Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-01/Krzysztof%20Gajos.png?itok=cTkXgpRN"},
        {   "id":1558,
            "name": "L Mahadevan",
            "researchInterests": ["Control Theory and Stochastic Systems|Modeling Physical/Biological Phenomena and Systems|Soft Matter|Biomechanics and Motor Control|Cell and Tissue Engineering, Biomaterials, and Therapeutics|Computational Neuroscience|Robotics and Control|Fluid Mechanics|Solid Mechanics|Surface and Interface Science"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "Lola England de Valpine Professor of Applied Mathematics, of Organismic and Evolutionary Biology, and of Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Mahadevan_200x300.jpg?itok=tWpajwl"},
        {   "id":1741,
            "name": "Lene V. Hau",
            "researchInterests": "Photonics",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Mallinckrodt Professor of Physics and of Applied Physics",
            "location": "Lyman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Hau_200x300.jpg?itok=FMAf4nNl"},
        {   "id":1536,
            "name": "Leslie G. Valiant",
            "researchInterests": ["Theory of Computation|Artificial Intelligence|Computational Neuroscience"],
            "teachingArea": "Computer Science",
            "primaryTitle": "T. Jefferson Coolidge Professor of Computer Science and Applied Mathematics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-12/Valiant_200x300_0.jpg?itok=P88qtWlC"},
        {   "id":1832,
            "name": "Madhu Sudan",
            "researchInterests": ["Theory of Computation|Theory of Communication"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Sudan_200x300.jpg?itok=8sN4kwQI"},
        {   "id":1675,
            "name": "Margo S Levine",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "Interim Director of Undergraduate Education - Academics",
            "location": "Pierce",
            "image": "https://projects.iq.harvard.edu/files/styles/profile_full/public/lifesci/files/margolevine.jpg?m=1534410901&itok=HxmrXx8C"},
        {   "id":2985,
            "name": "Marianna Katherine Linz",
            "researchInterests": ["Climate Change|Climate Dynamics|Meteorology|Oceanography|Fluid Mechanics"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Assistant Professor of Environmental Science and Engineering and of Earth and Planetary Sciences",
            "location": "26 Oxford St",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Linz_200x300.jpg?itok=-Jra_k2i"},
        {   "id":1541,
            "name": "Marko Loncar",
            "researchInterests": "Photonics",
            "teachingArea": "Applied Physics",
            "primaryTitle": "Tiantsai Lin Professor of Electrical Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Loncar_200x300.jpg?itok=HVt4L182"},
        {   "id":2724,
            "name": "Markus Thomas Basan",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Soft Matter"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Assistant Professor of Systems Biology; Affiliate in Applied Physics",
            "location": "Warren Alpert",
            "image": "https://projects.iq.harvard.edu/files/styles/profile_full/public/markusbasan/files/photo_markus_01.jpg?m=1573718176&itok=TAxCIbog"},
        {   "id":1532,
            "name": "Maurice Smith",
            "researchInterests": ["Robotics and Control|Modeling Physical/Biological Phenomena and Systems|Control Theory and Stochastic Systems|Computational Neuroscience|Biomechanics and Motor Control"],
            "teachingArea": "Bioengineering",
            "primaryTitle": "Gordon McKay Professor of Bioengineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Smith.Maurice_200x300_0.jpg?itok=3JNny3dk"},
        {   "id":13586,
            "name":	"Maxim Prigozhin",
            "researchInterests": ["Biomaterials|Soft Matter|Cell and Tissue Engineering, Biomaterials, and Therapeutics"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Assistant Professor of Molecular and Cellular Biology and of Applied Physics",
            "location": "Northwest Building",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-04/Maxim_Prigozhin_headshot%5B2%5D.jpg?itok=bMU4NdxR"},
        {   "id":1525,
            "name": "Michael B. McElroy",
            "researchInterests": ["Atmospheric Chemistry|Climate Change|Energy Resources and Energy Systems|Global Contaminants"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Gilbert Butler Professor of Environmental Studies",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/McElroy_200x300.jpg?itok=RjOgTDM5"},
        {   "id":1526,
            "name": "Michael D. Mitzenmacher",
            "researchInterests": ["Economics and Computation|Theory of Computation|Artificial Intelligence|Computational and Data Science|Systems, Networks, and Databases|Theory of Communication"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Thomas J. Watson, Sr. Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Mitzenmacher_200x300.jpg?itok=nZe6W10T"},
        {   "id":1562,
            "name": "Michael D. Smith",
            "researchInterests": ["Architecture|Programming Languages|Systems, Networks, and Databases|Computer Engineering and Architecture"],
            "teachingArea": "Computer Science",
            "primaryTitle": "John H. Finley, Jr. Professor of Engineering and Applied Sciences; Harvard University Distinguished Service Professor",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-01/Mike_Smith.png?itok=7WjjVrq6"},
        {   "id":1584,
            "name": "Michael J. Aziz",
            "researchInterests": ["Materials|Energy Resources and Energy Systems|Energy, Environment, and Sustainability"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Gene and Tracy Sykes Professor of Materials and Energy Technologies",
            "location":"Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/maziz_200x300.jpg?itok=xSzrvCNX"},
        {   "id":1556,
            "name": "Michael P. Brenner",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Soft Matter|Biomechanics and Motor Control|Fluid Mechanics"],
            "teachingArea": "Applied Mathematics",
            "primaryTitle": "Michael F. Cronin Professor of Applied Mathematics and Applied Physics and Professor of Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Brenner_200x300.jpg?itok=UBUFu6Lx"},
        {   "id":3141,
            "name": "Milind Tambe",
            "researchInterests": ["Economics and Computation|Artificial Intelligence|Information and Society"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-11/Milind_Tambe_headshot.jpg?itok=uQCXEtGk"},
        {   "id":2468,
            "name": "Minlan Yu",
            "researchInterests": ["Systems, Networks, and Databases"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Associate Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Yu_200x300.jpg?itok=0eMXtZsL"},
        {   "id":1764,
            "name":	"Na Li",
            "researchInterests": ["Robotics and Control|Modeling Physical/Biological Phenomena and Systems|Energy, Environment, and Sustainability|Economics and Computation|Control Theory and Stochastic Systems"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Gordon McKay Professor of Electrical Engineering and Applied Mathematics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/LiNa_200x300.jpg?itok=E9-LvEmP"},
        {   "id":3000,
            "name":	"Nada Amin",
            "researchInterests": ["Artificial Intelligence|Programming Languages"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Assistant Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2020-03/Amin.jpg?itok=QVYCFF9m"},
        {   "id":2624,
            "name": "Noel Michele Holbrook",
            "researchInterests": ["Biogeochemical Cycles|Climate Change|Water"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Charles Bullard Professor of Forestry; Affiliate in Environmental Science & Engineering",
            "location": "Bio. Labs",
            "image": "https://hwpi.harvard.edu/files/styles/profile_full/public/holbrook/files/holbrook.jpg?m=1599146111&itok=xnfBWRnY"},
        {   "id":2625,
            "name": "Paul R Moorcroft",
            "researchInterests": ["Biogeochemical Cycles|Climate Change|Water"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Professor of Organismic and Evolutionary Biology; Affiliate in Environmental Science & Engineering",
            "location": "26 Oxford St",
            "image": "https://hwpi.harvard.edu/files/styles/profile_full/public/moorcroftlab/files/prm_profile_pic_2015.jpg?m=1599179341&itok=QWkfukbS"},
        {   "id":1668,
            "name": "Pavlos Protopapas",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Artificial Intelligence|Computational and Data Science"],
            "teachingArea": ["Computer Science","Applied Computation"],
            "primaryTitle": "Scientific Program Director and Lecturer",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/protopapas_200x300.jpg?itok=-g8TD-do"},
        {   "id":1791,
            "name": "Peter John Huybers",
            "researchInterests": ["Climate Change|Climate Dynamics|Ice Dynamics and Sea Level|Oceanography"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Professor of Earth and Planetary Sciences and of Environmental Science and Engineering",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-11/Huybers_headshot.jpg?itok=9I1yxCmC"},
        {   "id":1799,
            "name":	"Philip Kim",
            "researchInterests": ["Materials|Quantum Engineering|Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Professor of Physics and of Applied Physics",
            "location": "LISE",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Kim_200x300.jpg?itok=sqUcl_Bt"},
        {   "id":1600,
            "name": "Philippe Cluzel",
            "researchInterests": ["Biomaterials|Biomechanics and Motor Control|Cell and Tissue Engineering, Biomaterials, and Therapeutics"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Professor of Molecular and Cellular Biology and Gordon McKay Professor of Applied Physics",
            "location": "Northwest Building",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Cluzel_200x300.jpg?itok=gD3P1UFi"},
        {   "id":1889,
            "name": "Prineha Narang",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Materials|Quantum Engineering|Computational and Data Science|Surface and Interface Science"],
            "teachingArea":	"Materials Science & Mechanical Engineering",
            "primaryTitle": "Assistant Professor of Computational Materials Science",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Narang_200x300_0.jpg?itok=Z4IGFTqV"},
        {   "id":1569,
            "name": "Radhika Nagpal",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Bioinspired Robotics and Computing|Artificial Intelligence|Programming Languages"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Fred Kavli Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Nagpal_200x300.jpg?itok=LhPXeZfg"},
        {   "id":1765,
            "name": "Richard McCullough",
            "researchInterests": null,
            "teachingArea":	"Materials Science & Mechanical Engineering",
            "primaryTitle": "Vice Provost for Research",
            "location": "The Richard A. and Susan F. Smith Campus Center",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/McCullough_200x300.jpg?itok=3iGNKPl3"},
        {   "id":1555,
            "name": "Robert D. Howe",
            "researchInterests": ["Bioinspired Robotics and Computing|Biomechanics and Motor Control|Robotics and Control"],
            "teachingArea":	"Materials Science & Mechanical Engineering",
            "primaryTitle": "Abbott and James Lawrence Professor of Engineering",
            "location": "60 Oxford St",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Howe_200x300.jpg?itok=mzbzGtM2"},
        {   "id":1537,
            "name": "Robert J. Wood",
            "researchInterests": ["Bioinspired Robotics and Computing|Biomechanics and Motor Control|Artificial Intelligence|Robotics and Control"],
            "teachingArea":	"Materials Science & Mechanical Engineering",
            "primaryTitle": "Charles River Professor of Engineering and Applied Sciences",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Wood_200x300.jpg?itok=MAF5J5Bt"},
        {   "id":1585,
            "name": "Robert M. Westervelt",
            "researchInterests": "Quantum Engineering",
            "teachingArea":	"Applied Physics",
            "primaryTitle": "Mallinckrodt Professor of Applied Physics and of Physics",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Westervelt_200x300.jpg?itok=XUwaz3Z7"},
        {   "id":1807,
            "name": "Robin Wordsworth",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Climate Dynamics|Meteorology|Planetary Sciences|Solar Geoengineering|Fluid Mechanics|Solid Mechanics"],
            "teachingArea":	"Environmental Science & Engineering",
            "primaryTitle": "Associate Professor of Environmental Science and Engineering",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Wordsworth_200x300.jpg?itok=3iuqwuUn"},
        {   "id":1853,
            "name": "Roy G. Gordon",
            "researchInterests": ["Materials|Energy, Environment, and Sustainability"],
            "teachingArea":	"Materials Science & Mechanical Engineering",
            "primaryTitle": "Thomas Dudley Cabot Professor of Chemistry and Professor of Materials Science",
            "location": "Converse Laboratory",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Gordon_200x300_0.jpg?itok=EzcfrEcP"},
        {   "id":1521,
            "name": "Salil P. Vadhan",
            "researchInterests": ["Theory of Computation|Computational and Data Science|Information and Society"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Vicky Joseph Professor of Computer Science and Applied Mathematics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-12/Vadhan_200x300.jpg?itok=5bjZDyCG"},
        {   "id":1884,
            "name": "Samir Mitragotri",
            "researchInterests": ["Materials|Cell and Tissue Engineering, Biomaterials, and Therapeutics|Science and Engineering Education"],
            "teachingArea":	"Bioengineering",
            "primaryTitle": "Hiller Professor of Bioengineering and Hansjorg Wyss Professor of Biologically Inspired Engineering",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/mitragotri_200x300.jpg?itok=CdqEJvsW"},
        {   "id":1567,
            "name": "Scot T. Martin",
            "researchInterests": ["Atmospheric Chemistry|Biogeochemical Cycles|Climate Change|Global Contaminants"],
            "teachingArea":	"Environmental Science & Engineering",
            "primaryTitle": "Gordon McKay Professor of Environmental Science and Engineering and Professor of Earth and Planetary Sciences",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/2019-12/Martin_200x300.png?itok=yruqon38"},
        {   "id":1588,
            "name": "Sharad Ramanathan",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Biomaterials|Soft Matter|Cell and Tissue Engineering, Biomaterials, and Therapeutics|Computational and Data Science|Computational Neuroscience|Surface and Interface Science"],
            "teachingArea":	"Applied Physics",
            "primaryTitle": "Llura and Gordon Gund Professor of Neurosciences and of Molecular and Cellular Biology and Professor of Applied Physics and Stem Cell and Regenerative Biology",
            "location": "Northwest Building",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Ramanathan.Sharad_200x300.jpg?itok=H5DrvjiH"},
        {   "id":22051,
            "name": "Stephanie Gil",
            "researchInterests": ["Artificial Intelligence|Systems, Networks, and Databases|Robotics and Control"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Assistant Professor of Computer Science",
            "location": null,
            "image": "https://projects.iq.harvard.edu/files/styles/os_files_medium/public/ajk_529a-214x300.jpg?m=1597097057&itok=rQnWy-2w"},
        {   "id":1605,
            "name": "Stephen Chong",
            "researchInterests": ["Information and Society|Programming Languages"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Chong_200x300.jpg?itok=xxmcmc4m"},
        {   "id":1531,
            "name": "Steven C. Wofsy",
            "researchInterests": ["Biogeochemical Cycles|Climate Change|Global Contaminants"],
            "teachingArea":	"Environmental Science & Engineering",
            "primaryTitle": "Abbott Lawrence Rotch Professor of Atmospheric and Environmental Science",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Wofsy_200x300_0.jpg?itok=3XssrMxQ"},
        {   "id":1565,
            "name": "Steven J. Gortler",
            "researchInterests": ["Graphics, Vision, Visualization, and Interaction"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Robert I. Goldman Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Gortler_200x300.jpg?itok=59MOY-6M"},
        {   "id":1759,
            "name": "Stratos Idreos",
            "researchInterests": ["Systems, Networks, and Databases|Computational and Data Science"],
            "teachingArea":	"Computer Science",
            "primaryTitle": "Associate Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Idreos_200x300.jpg?itok=cRX2oC4r"},
        {   "id":1557,
            "name": "Stuart M. Shieber",
            "researchInterests": "Artificial Intelligence",
            "teachingArea":	"Computer Science",
            "primaryTitle": "James O. Welch, Jr. and Virginia B. Welch Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Shieber_200x300.jpg?itok=iY1X7grC"},
        {   "id": 1886,
            "name": "Susan A Murphy",
            "researchInterests": "Artificial Intelligence",
            "teachingArea":	"Computer Science",
            "primaryTitle": "Professor of Statistics and of Computer Science",
            "location": "Science Center",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Murphy_200x300.jpg?itok=7OTnx0Lu"},
        {   "id": 1573,
            "name": "Tai T. Wu",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Gordon McKay Professor of Applied Physics and Professor of Physics",
            "location": "Pierce",
            "image": "https://projects.iq.harvard.edu/files/styles/profile_full/public/physics/files/wu.png?m=1577988070&itok=7GvBw9Fu"},
        {   "id": 1534,
            "name": "Todd Zickler",
            "researchInterests": ["Signal Processing|Graphics, Vision, Visualization, and Interaction|Artificial Intelligence"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "William and Ami Kuan Danoff Professor of Electrical Engineering and Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/zickler_200x300.jpg?itok=9cP5wruW"},
        {   "id": 1583,
            "name": "Venkatesh Narayanamurti",
            "researchInterests": ["Materials|Surface and Interface Science|Energy, Environment, and Sustainability|Science and Engineering Education|Science and Technology Policy"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Benjamin Peirce Research Professor of Technology and Public Policy",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Narayanamurti_200x300.jpg?itok=Fqwb1hna"},
        {   "id": 2728,
            "name": "Vijay Janapa Reddi",
            "researchInterests": ["Architecture|Artificial Intelligence|Programming Languages|Systems, Networks, and Databases|Computer Engineering and Architecture|Robotics and Control"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Associate Professor of Electrical Engineering",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Reddi_200x300.jpg?itok=vKzbuTUW"},
        {   "id": 1552,
            "name": "Vinothan N. Manoharan",
            "researchInterests": ["Materials|Soft Matter|Surface and Interface Science"],
            "teachingArea": "Applied Physics",
            "primaryTitle": "Wagner Family Professor of Chemical Engineering and Professor of Physics",
            "location": "Lyman",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Manoharan_200x300.jpg?itok=hlTgtINN"},
        {   "id": 1564,
            "name": "Woodward Yang",
            "researchInterests": ["Architecture|Artificial Intelligence|Graphics, Vision, Visualization, and Interaction|Information and Society|Circuits and VLSI|Computer Engineering and Architecture|Signal Processing|Communications and Internet Policy|Design and Innovation|Energy, Environment, and Sustainability|Science and Engineering Education|Science and Technology Policy"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Gordon McKay Professor of Electrical Engineering and Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Yang_200x300.jpg?itok=aD_UeiZ_"},
        {   "id": 1823,
            "name": "Xin Li",
            "researchInterests": ["Materials|Artificial Intelligence|Computational and Data Science|Energy Resources and Energy Systems|Surface and Interface Science|Energy, Environment, and Sustainability"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Associate Professor of Materials Science",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Li_200x300.jpg?itok=6Ok4g-Gm"},
        {   "id": 1713,
            "name": "Yaron Singer",
            "researchInterests": ["Economics and Computation|Theory of Computation|Artificial Intelligence"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science and Applied Mathematics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Singer__200x300.jpg?itok=4oohimr"},
        {   "id": 1519,
            "name": "Yiling Chen",
            "researchInterests": ["Economics and Computation|Artificial Intelligence"],
            "teachingArea": "Computer Science",
            "primaryTitle": "Gordon McKay Professor of Computer Science",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Chen_200x300.jpg?itok=vDc7-KbC"},
        {   "id": 1651,
            "name": "Yue Lu",
            "researchInterests": ["Signal Processing|Modeling Physical/Biological Phenomena and Systems|Control Theory and Stochastic Systems"],
            "teachingArea": "Electrical Engineering",
            "primaryTitle": "Gordon McKay Professor of Electrical Engineering and of Applied Mathematics",
            "location": "Maxwell Dworkin",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/yuelu200x300.png?itok=uhVmGhwJ"},
        {   "id": 1553,
            "name": "Zhigang Suo",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems|Materials|Soft Matter"],
            "teachingArea": "Materials Science & Mechanical Engineering",
            "primaryTitle": "Allen E. and Marilyn M. Puckett Professor of Mechanics and Materials",
            "location": "Pierce",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Suo_200x300.jpg?itok=uTIcxakH"},
        {   "id": 1572,
            "name": "Zhiming Kuang",
            "researchInterests": ["Modeling Physical/Biological Phenomena and Systems", "Climate Change","Climate Dynamics","Meteorology"],
            "teachingArea": "Environmental Science & Engineering",
            "primaryTitle": "Gordon McKay Professor of Atmospheric and Environmental Science",
            "location": "Geological Museum",
            "image": "http://seasdrupalstg.prod.acquia-sites.com/sites/default/files/styles/headshot_2x/public/images/Directory/Kuang_200x300.jpg?itok=lOkYF2Ix"}

    ],

    // relationships from newspaper tags
    // removed awards and fellowships and people whose names did not appear in the faculty cards
    // TODO - incorporate publication relationships
    "links": [
        {"source": 1519, "target": 1636, "weight": 1, "type": "news"},
        {"source": 1526, "target": 1533, "weight": 1, "type": "news"},
        {"source": 1531, "target": 1732, "weight": 1, "type": "news"},
        {"source": 1534, "target": 1561, "weight": 1, "type": "news"},
        {"source": 1534, "target": 1566, "weight": 1, "type": "news"},
        {"source": 1534, "target": 1580, "weight": 1, "type": "news"},
        {"source": 1537, "target": 1563, "weight": 1, "type": "news"},
        {"source": 1537, "target": 1731, "weight": 1, "type": "news"},
        {"source": 1541, "target": 1527, "weight": 1, "type": "news"},
        {"source": 1541, "target": 1566, "weight": 1, "type": "news"},
        {"source": 1541, "target": 1580, "weight": 1, "type": "news"},
        {"source": 1541, "target": 1762, "weight": 1, "type": "news"},
        {"source": 1552, "target": 1556, "weight": 2, "type": "news"},
        {"source": 1552, "target": 1580, "weight": 1, "type": "news"},
        {"source": 1552, "target": 1627, "weight": 1, "type": "news"},
        {"source": 1553, "target": 1733, "weight": 1, "type": "news"},
        {"source": 1556, "target": 1544, "weight": 2, "type": "news"},
        {"source": 1556, "target": 1584, "weight": 1, "type": "news"},
        {"source": 1558, "target": 1715, "weight": 1, "type": "news"},
        {"source": 1564, "target": 1555, "weight": 1, "type": "news"},
        {"source": 1566, "target": 1551, "weight": 2, "type": "news"},
        {"source": 1577, "target": 1545, "weight": 1, "type": "news"},
        {"source": 1584, "target": 1566, "weight": 1, "type": "news"},
        {"source": 1585, "target": 1765, "weight": 1, "type": "news"},
        {"source": 1598, "target": 1527, "weight": 1, "type": "news"},
        {"source": 1598, "target": 1548, "weight": 1, "type": "news"},
        {"source": 1598, "target": 2715, "weight": 1, "type": "news"},
        {"source": 1605, "target": 1544, "weight": 1, "type": "news"},
        {"source": 1732, "target": 1688, "weight": 1, "type": "news"},
        {"source": 1765, "target": 1544, "weight": 1, "type": "news"},
        {"source": 1791, "target": 1531, "weight": 1, "type": "news"},
        {"source": 1802, "target": 1713, "weight": 1, "type": "news"},
        {"source": 1832, "target": 1822, "weight": 1, "type": "news"},
        {"source": 2414, "target": 1554, "weight": 1, "type": "news"},
        {"source": 1541, "target": 1545, "weight": 1, "type": "news"},
        {"source": 1566, "target": 1545, "weight": 1, "type": "news"},
        {"source": 1564, "target": 1577, "weight": 1, "type": "news"},
        {"source": 1564, "target": 1523, "weight": 1, "type": "news"},
        {"source": 1555, "target": 1577, "weight": 1, "type": "news"},
        {"source": 1577, "target": 1523, "weight": 1, "type": "news"},
        {"source": 1584, "target": 1551, "weight": 1, "type": "news"},
        {"source": 1566, "target": 1551, "weight": 1, "type": "news"},
        {"source": 1802, "target": 1534, "weight": 1, "type": "news"},
        {"source": 1713, "target": 1534, "weight": 1, "type": "news"},
        {"source": 1832, "target": 1835, "weight": 1, "type": "news"},
        {"source": 1822, "target": 1835, "weight": 1, "type": "news"},
        {"source": 1762, "target": 1799, "weight": 1, "type": "research"},
        {"source": 1762, "target": 1889, "weight": 1, "type": "research"},
        {"source": 13261, "target": 1727, "weight": 1,  "type": "research"},
        {"source": 13261, "target": 1519, "weight":1, "type":"research"},


    ]
}